[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/competitive"
  to   = "/competitive/index.html"
  status = 200

[[redirects]]
  from = "/no-competition"
  to   = "/no-competition/index.html"
  status = 200

[[redirects]]
  from = "/team"
  to   = "/team/index.html"
  status = 200
